In [1]:
from sklearn import datasets

In [2]:
digits = datasets.load_digits()

In [3]:
print digits.target[0]

0


In [4]:
print digits.images[0]

[[  0.   0.   5.  13.   9.   1.   0.   0.]
 [  0.   0.  13.  15.  10.  15.   5.   0.]
 [  0.   3.  15.   2.   0.  11.   8.   0.]
 [  0.   4.  12.   0.   0.   8.   8.   0.]
 [  0.   5.   8.   0.   0.   9.   8.   0.]
 [  0.   4.  11.   0.   1.  12.   7.   0.]
 [  0.   2.  14.   5.  10.  12.   0.   0.]
 [  0.   0.   6.  13.  10.   0.   0.   0.]]


In [5]:
print 'Feature Vector', digits.images[0].reshape(-1, 64)

Feature Vector [[  0.   0.   5.  13.   9.   1.   0.   0.   0.   0.  13.  15.  10.  15.
    5.   0.   0.   3.  15.   2.   0.  11.   8.   0.   0.   4.  12.   0.
    0.   8.   8.   0.   0.   5.   8.   0.   0.   9.   8.   0.   0.   4.
   11.   0.   1.  12.   7.   0.   0.   2.  14.   5.  10.  12.   0.   0.
    0.   0.   6.  13.  10.   0.   0.   0.]]


# Extracting points of interest as features

points of interest, are points that are surrounded by rich textures and can be reproduced despite perturbing the images. ```Edges and corners``` are two common types of points of interest.

# Scale-Invariant Feature Transform

SIFT is a method for extracting features from an image that is less sensitive to the scale, rotation, and illumination of the image than the extraction methods we have previously discussed.

# Speeded-Up Robust Features 

SURF is another method of extracting interesting points of an image and creating descriptions that are invariant of the image's scale, orientation, and illumination. SURF can be computed more quickly than SIFT, and it is more effective at recognizing features across images that have been transformed in certain ways.

# Data standardization
Many estimators perform better when they are trained on standardized data sets. Standardized data has zero mean and unit variance. 

In [6]:
from sklearn import preprocessing
import numpy as np
X = np.array([
[0., 0., 5., 13., 9., 1.],
[0., 0., 13., 15., 10., 15.],
[0., 3., 15., 2., 0., 11.]
])
print preprocessing.scale(X)

[[ 0.         -0.70710678 -1.38873015  0.52489066  0.59299945 -1.35873244]
 [ 0.         -0.70710678  0.46291005  0.87481777  0.81537425  1.01904933]
 [ 0.          1.41421356  0.9258201  -1.39970842 -1.4083737   0.33968311]]


In [7]:
help(preprocessing.scale)

Help on function scale in module sklearn.preprocessing.data:

scale(X, axis=0, with_mean=True, with_std=True, copy=True)
    Standardize a dataset along any axis
    
    Center to the mean and component wise scale to unit variance.
    
    Read more in the :ref:`User Guide <preprocessing_scaler>`.
    
    Parameters
    ----------
    X : {array-like, sparse matrix}
        The data to center and scale.
    
    axis : int (0 by default)
        axis used to compute the means and standard deviations along. If 0,
        independently standardize each feature, otherwise (if 1) standardize
        each sample.
    
    with_mean : boolean, True by default
        If True, center the data before scaling.
    
    with_std : boolean, True by default
        If True, scale the data to unit variance (or equivalently,
        unit standard deviation).
    
    copy : boolean, optional, default True
        set to False to perform inplace row normalization and avoid a
        copy (if the i